<?php
/**
 * @file(checkga.module)
 */

/**
 * Implements hook_permission()
 */
function checkga_permission() {
  return array (
    'administer_checkga' => array (
      'title' => t('Administer the Check Google Analytics module')
    ),
  );
} // checkga_permission()

/**
 * Implements hook_menu()
 */
function checkga_menu() {
  return array (
    // The admin config page for the module
    'admin/config/checkga' => array (
      'title' => t('Check Google Analytics Module'),
      'description' => t('Administer Check Google Analytics Module'),
      'access arguments' => array ('administer_checkga'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array ('checkga_admin_settings_form'),
    )
  );
} // hook_menu()

/**
 * Implements hook_form()
 */
function checkga_admin_settings_form($node, &$form_state) {

  $form = array();

  $form['overview'] = array(
    '#markup' => '<h3>'.t('Configuration for the Check Google Analytics Module').'</h3>',
  );

  $form['checkga_prodURL'] = array(
    '#type' => 'textfield',
    '#title' => t('The URL of your production server:'),
    '#default_value' => variable_get('checkga_prodURL', $_SERVER['HTTP_HOST']),
    '#description' => t('The URL of your production server *without* its protocol (example: mydomain.com). Google Analytics will be enabled on this domain and dissabled on other (non-production) domains.'),
    '#required' => TRUE,
  );

  $footertext = variable_get('checkga_footertext') ?: t('This text shows up in the footer.');

  $form['checkga_footertext'] = array(
    '#type' => 'text_format',
    '#title' => t('Optional Privacy Notice'),
    '#description' => t('Optional. A privacy notice that will be attached to the footer on your site.'),
    '#rows' => 10,
    '#default_value' => $footertext['value'] ?: t('This text shows up in the footer.')
  );

  return system_settings_form($form);

} // checkga_admin_settings_form()

/**
 * Validates some of the form values.
 */
function checkga_admin_settings_form_validate($form, &$form_state) {
  if (filter_var('http://'.$form_state['values']['checkga_prodURL'], FILTER_VALIDATE_URL) === FALSE) {
    form_set_error('checkga_prodURL', t('Please provide a valid URL without protocols (http:// OR https://)'));
  }
}

/**
 * Implements hook_init()
 */
function checkga_init() {

  // Check if we are on a production server
  if ($_SERVER['HTTP_HOST'] == variable_get('checkga_prodURL', 'mydomain.com')) {

    // Check if the Google Analytics module is turned on and/or installed
    if (!module_exists('googleanalytics')) {

      drupal_set_message('Warning: The <a href="/admin/modules">Google Analytics Module</a> was not enabled and/or installed. As this is a production server, the Google Analytics module should be enabled. I\'ll attempt to enable it for you now...', 'warning', FALSE);

      if (module_enable(array('googleanalytics'), FALSE)) {
        drupal_set_message(t('Sucess! The Google Analytics module has been restored to its healthy self!'));
      } else {
        drupal_set_message(t('Error: I was unable to enable the Google Analytics module (or one of its dependancies) for you.'), 'error', FALSE);
      }

    }

  } else { // we are *NOT* on a production server

    // Check if the Google Analytics module is turned on for some reason
    if (module_exists('googleanalytics')) {

      module_disable(array('googleanalytics'), TRUE);

      drupal_set_message('Warning: The <a href="/admin/modules">Google Analytics Module</a> was enabled for some reason. As this is NOT a production server, the Google Analytics module should NOT be enabled. I\'ve disabled it for you, but please <a href="/admin/modules">confirm this</a>.', 'warning', FALSE);

    }

  }

  $footertext = variable_get('checkga_footertext', FALSE);
  $output = $footertext['value'] ?: '<!-- Check Google Analytics module: There is no text set in the Optional Privacy Notice. See: /admin/config/checkga to set it. -->';

  // I just used drupal_add_region_content() here. One could also create a block and place it in a region programatically.
  drupal_add_region_content('footer', '<div id="checkga_privacynotice">'.$output.'</div>');

} // checkga_init()
